name: Release
on:
  workflow_dispatch:
        inputs:
                tag:
                        description: 'Version TAG'
                        required: true
                        type: string
jobs:
  
  release-version:
    env:
        TAG_VERSION: ${{github.event.inputs.tag}}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
        - uses: actions/checkout@v4
        - name: Configuring git user
          run: |
               git config --local user.email "actions@github.com"
               git config --local user.name "Github Actions"
        - name: Building Docker Image
          run: |
               docker build -t sshlog-build --target builder .
               
        - name: Extracting RPM and DEB
          run: |
               mkdir -p releases
               docker run -v ./releases:/releases sshlog-build cp /build/sshlog_1.0.0_amd64.deb /releases

        - name: Tagging Repo
          run: |
               git tag -a ${TAG_VERSION} -m  ${TAG_VERSION}
               git push --tags
        - name: Releasing
          run: |
               gh release create --verify-tag ${TAG_VERSION} releases/*
               
               
